build:
    environment:
        php:
            version: 5.5.9 # Common versions: 5.4, 5.5, 5.6, 7.0 or hhvm
    tests:
        override:
            -
                command: 'phpunit --bootstrap vendor/autoload.php --coverage-clover coverage.xml tests'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            before_parentheses:
                function_declaration: true
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
